version: '3'

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: confluence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    networks:
      confnetwork:
        ipv4_address: 10.0.0.11

  confluence-server:
    depends_on:
      - postgresql
    image: atlassian/confluence
    ports:
      - 80:8090
      - 81:8091
    volumes:
      - /data/confluence:/var/atlassian/application-data/confluence
    networks:
      confnetwork:
        ipv4_address: 10.0.0.5

networks:
  confnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24