version: '3'

services:
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
    networks:
      confnetwork:
        ipv4_address: 10.0.0.11

  jira-server:
    depends_on:
      - postgresql
    image: atlassian/jira-software
    ports:
      - 80:8080      
    volumes:
      - /data/jira:/var/atlassian/application-data/jira
    networks:
      confnetwork:
        ipv4_address: 10.0.0.5

networks:
  confnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
